class ReportService {
  constructor() {
    this.supabase = window.supabaseClient;
  }

  async generateCompliancePDF() {
    try {
      const { jsPDF } = window.jspdf;
      const doc = new jsPDF();

      const profile = await window.userService.getProfile();
      const animals = await window.animalService.getAnimals();
      const treatments = await window.treatmentService.getTreatments();
      const amuData = await window.dashboardService.getAMUTrends(6);

      // Header
      doc.setFillColor(5, 150, 105); // Emerald 600
      doc.rect(0, 0, 210, 40, 'F');

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.text("PashuRaksha Compliance Audit", 20, 25);

      doc.setFontSize(10);
      doc.text(`Generated on: ${new Date().toLocaleString()}`, 140, 25);

      // Farmer Details
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(14);
      doc.text("Farmer Details", 20, 55);
      doc.line(20, 57, 60, 57);

      doc.setFontSize(10);
      doc.text(`Name: ${profile.full_name}`, 20, 65);
      doc.text(`Farm Name: ${profile.farm_name}`, 20, 72);
      doc.text(`Location: ${profile.village}, ${profile.district}, ${profile.state}`, 20, 79);
      doc.text(`Contact: ${profile.phone || 'N/A'}`, 20, 86);

      // Livestock Summary
      doc.setFontSize(14);
      doc.text("Livestock Summary", 120, 55);
      doc.line(120, 57, 165, 57);

      doc.setFontSize(10);
      const healthyCount = animals.filter(a => (a.health_status || '').toLowerCase() === 'healthy').length;
      doc.text(`Total Animals: ${animals.length}`, 120, 65);
      doc.text(`Healthy Animals: ${healthyCount}`, 120, 72);
      doc.text(`Under Treatment: ${animals.length - healthyCount}`, 120, 79);

      // MRL Compliance Table
      doc.setFontSize(14);
      doc.text("MRL & Treatment Logs", 20, 105);

      const tableData = treatments.map(t => {
        const med = t.medicines;
        const medName = med ? med.medicine_name : 'Unknown';
        let mrlStatus = "N/A";
        if (med) {
          const withdrawalDays = med.withdrawal_days || 0;
          const status = getMRLStatus(t.start_date, withdrawalDays);
          mrlStatus = status && status.status === 'Safe' ? 'SAFE' : (status ? `RESTRICTED (${status.remaining}d)` : 'RESTRICTED');
        }
        return [
          new Date(t.start_date).toLocaleDateString(),
          t.animals?.animal_code || t.animal_id || 'Unknown',
          medName,
          t.dosage || 'N/A',
          mrlStatus
        ];
      });

      doc.autoTable({
        startY: 110,
        head: [['Date', 'Animal ID', 'Medicine', 'Dosage', 'MRL Status']],
        body: tableData,
        headStyles: { fillColor: [5, 150, 105] },
        alternateRowStyles: { fillColor: [240, 253, 244] }
      });

      // AMU Trends Summary
      const finalY = doc.lastAutoTable.finalY + 15;
      doc.setFontSize(14);
      doc.text("AMU Usage Summary (Last 6 Months)", 20, finalY);
      doc.setFontSize(10);
      doc.text(`Total Antibiotic Doses: ${amuData.totalAntibiotics}`, 20, finalY + 10);
      doc.text(`Total Vaccination Doses: ${amuData.totalVaccines}`, 20, finalY + 17);

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text("This report is generated by PashuRaksha Digital Farm Management System.", 20, 285);
      doc.text("Verified secure batch compliance audit.", 150, 285);

      doc.save(`PashuRaksha_Compliance_Report_${new Date().toISOString().split('T')[0]}.pdf`);
      window.showToast('Compliance report downloaded!', 'success');

    } catch (error) {
      console.error('PDF Generation Error:', error);
      window.showToast('Failed to generate PDF: ' + error.message, 'error');
    }
  }

  async generateSafeBatchQR() {
    try {
      const treatments = await window.treatmentService.getTreatments();
      const profile = await window.userService.getProfile();

      // Check if any animal is under restriction
      let restrictedCount = 0;
      treatments.forEach(t => {
        const med = t.medicines;
        if (med) {
          const withdrawalDays = med.withdrawal_days || 0;
          const status = getMRLStatus(t.start_date, withdrawalDays);
          if (status && status.status === 'Restricted') restrictedCount++;
        }
      });

      if (restrictedCount > 0) {
        window.showToast(`Cannot generate safe badge. ${restrictedCount} animals are currently under MRL restriction.`, 'error');
        return;
      }

      const batchId = 'PR-' + Math.random().toString(36).substr(2, 9).toUpperCase();
      const traceUrl = `${window.location.origin}/trace.html?batch=${batchId}&farm=${encodeURIComponent(profile.farm_name)}`;

      const qrDataUrl = await QRCode.toDataURL(traceUrl, { width: 300, margin: 2 });

      this.showQRModal(qrDataUrl, batchId, profile);

    } catch (error) {
      console.error('QR Generation Error:', error);
      window.showToast('Failed to generate QR Badge.', 'error');
    }
  }

  showQRModal(qrUrl, batchId, profile) {
    const container = document.getElementById('modal-container');
    container.innerHTML = `
      <div class="fixed inset-0 bg-gray-900/50 backdrop-blur-sm flex justify-center items-center z-50 fade-in">
        <div class="bg-white rounded-3xl shadow-2xl w-full max-w-md p-8 m-4 relative text-center slide-up">
          <button onclick="document.getElementById('modal-container').innerHTML=''" class="absolute top-4 right-4 p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg">
            <i data-lucide="x" class="w-5 h-5"></i>
          </button>
          
          <div class="mb-6">
            <h3 class="text-2xl font-bold text-gray-800 brand-font">Safe Batch Badge</h3>
            <p class="text-sm text-emerald-600 font-bold uppercase tracking-widest mt-1">Certified MRL Compliant</p>
          </div>

          <div class="bg-emerald-50 p-4 rounded-2xl mb-6 inline-block">
            <img src="${qrUrl}" alt="QR Code" class="w-48 h-48 mx-auto shadow-sm rounded-lg border-4 border-white">
          </div>

          <div class="text-left bg-gray-50 p-4 rounded-xl mb-6 space-y-2">
            <div class="flex justify-between text-xs">
              <span class="text-gray-500">Farm:</span>
              <span class="font-bold text-gray-800">${profile.farm_name}</span>
            </div>
            <div class="flex justify-between text-xs">
              <span class="text-gray-500">Batch ID:</span>
              <span class="font-mono font-bold text-primary">${batchId}</span>
            </div>
            <div class="flex justify-between text-xs">
              <span class="text-gray-500">Verified On:</span>
              <span class="font-bold text-gray-800">${new Date().toLocaleDateString()}</span>
            </div>
          </div>

          <div class="flex flex-col space-y-3">
            <a href="${qrUrl}" download="PashuRaksha_Safe_Badge_${batchId}.png" class="w-full bg-primary hover:bg-primary-dark text-white py-3 rounded-xl font-bold shadow-lg transition-all flex items-center justify-center space-x-2">
              <i data-lucide="download" class="w-4 h-4"></i>
              <span>Download Badge</span>
            </a>
            <button onclick="navigator.clipboard.writeText('${batchId}'); window.showToast('ID Copied!', 'info');" class="w-full py-2.5 border border-gray-200 rounded-xl text-gray-600 font-medium hover:bg-gray-50 transition-colors text-sm">
              Copy Traceability ID
            </button>
          </div>
        </div>
      </div>
    `;
    if (window.lucide) window.lucide.createIcons();
  }
}

window.reportService = new ReportService();
